services:
  db:
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - prod.env

  nginx:
    build: nginx
    ports:
      - "80:80"

  web:
    build:
      context: ./dota2site
      args:
        ENV: prod
    environment:
      ENV: prod
    env_file:
      - prod.env
