services:
  db:
    image: postgres
    container_name: db
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - net2

  web:
    container_name: web
    command: gunicorn --bind 0.0.0.0:8000 dota2site.wsgi
    volumes:
      - static_volume:/staticfiles
    depends_on:
      - db
    networks:
      - net1
      - net2

  nginx:
    container_name: nginx
    volumes:
      - static_volume:/staticfiles
    depends_on:
      - web
    networks:
      - net1

networks:
  net1:
  net2:

volumes:
  static_volume:
  pgdata: