services:
  db:
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - dev.env

  nginx:
    image: nginx:1.29.0
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  web:
    build:
      context: ./dota2site
      args:
        ENV: dev
    volumes:
      - ./dota2site:/app
    environment:
      ENV: dev
    env_file:
      - dev.env
