services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - net2

  web:
    build: ./dota2site
    command: python manage.py runserver 0.0.0.0:8000
    container_name: web
    volumes:
      - ./dota2site:/app
      - static_volume:/app/staticfiles
    env_file:
      - dev.env
    depends_on:
      - db
    networks:
      - net1
      - net2

  nginx:
    container_name: nginx
    image: nginx:1.29.0
    volumes:
      - ./nginx/docker.nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/staticfiles
    depends_on:
      - web
    networks:
      - net1
    ports:
      - "80:80"

networks:
  net1:
  net2:

volumes:
  static_volume:
  pgdata: