# Generated by Django 5.2 on 2025-06-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota2builds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
