# Generated by Django 5.2 on 2025-05-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota2builds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_name',
            field=models.CharField(blank=True),
        ),
    ]
