# Generated by Django 5.2 on 2025-06-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota2builds', '0002_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, upload_to='upload/items'),
        ),
        migrations.DeleteModel(
            name='ItemDescription',
        ),
    ]
