# Generated by Django 5.2 on 2025-07-11 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota2builds', '0002_remove_item_image_alter_build_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builditeminfo',
            name='build',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemsinfo', to='dota2builds.build'),
        ),
        migrations.AlterUniqueTogether(
            name='builditeminfo',
            unique_together={('build', 'item')},
        ),
    ]
