# Generated by Django 5.2 on 2025-05-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota2builds', '0002_item_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_name',
            field=models.SlugField(blank=True),
        ),
    ]
