# Generated by Django 5.2 on 2025-06-04 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dota2builds', '0004_alter_build_name_alter_character_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Character',
            new_name='Hero',
        ),
        migrations.RenameField(
            model_name='build',
            old_name='character',
            new_name='hero',
        ),
    ]
