# Generated by Django 5.2 on 2025-06-23 15:28

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('dota2builds', '0005_rename_character_hero_rename_character_build_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
