# Generated by Django 5.2 on 2025-06-23 15:28

from django.db import migrations
from django.utils.text import slugify


def fill_slug(apps, schema_editor):
    Hero = apps.get_model("dota2builds", "Hero")
    for hero in Hero.objects.all():
        hero.slug = slugify(hero.name).lower().replace('-', '')
        hero.save()


def remove_slug(apps, schema_editor):
    Hero = apps.get_model("dota2builds", "Hero")
    for hero in Hero.objects.all():
        hero.slug = ""
        hero.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dota2builds', '0006_hero_slug'),
    ]

    operations = [
        migrations.RunPython(fill_slug, remove_slug)
    ]
