# Generated by Django 5.2 on 2025-06-26 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota2builds', '0007_hero_slug_fill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='build',
            name='items',
        ),
        migrations.CreateModel(
            name='BuildItemOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dota2builds.build')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dota2builds.item')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
