# Generated by Django 5.2 on 2025-06-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota2builds', '0008_remove_build_items_builditemorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='items',
            field=models.ManyToManyField(through='dota2builds.BuildItemOrder', to='dota2builds.item'),
        ),
    ]
